import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';
import { Lato } from 'next/font/google';

const arialMt = localFont({
  src: './fonts/arialmt.ttf',
  variable: '--font-arialMt',
  weight: '100 200 400 700 900',
});

const lato = Lato({
  variable: '--font-lato',
  subsets: ['latin'],
  weight: ['400', '700', '900'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${arialMt.variable} ${lato.variable} antialiased`}>{children}</body>
    </html>
  );
}
